[paths]
# outputs
# relative to the location of the script
odir = "../data/battlecreek/" # root directory for outputs

[raster_files]
# inputs
# raster file paths
# relative to the location of the script
elevation_file = "../data/battlecreek/elevation.tif" 
precip_file = "../data/battlecreek/wet_precip.tif" 
transmissivity_file = "../data/battlecreek/soil.tif" 
bulk_density_file = "../data/battlecreek/bulk_density.tif" 

[constants]
# constants that are used in the model
water_density = 1000.0 # kg/m^3
water_viscosity = 1.31e-6 # m^2/s 
seconds_per_day = 86400.0 # s/d
gravitational_acceleration = 9.81 # m/s^2

[variables]
# variables that can be changed to run different scenarios
k = 10000
tau = 16
psi = 0.35
